<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="playlist_css.css"?>

<!DOCTYPE
playlist
[
<!ELEMENT 
playlist (text, heading, title, track, path)
text (heading, title)
>

<!ELEMENT text  	(#PCDATA)>
<!ELEMENT heading   (#PCDATA)>
<!ELEMENT track 	(#PCDATA)>
<!ELEMENT path  	(#PCDATA)>
<!ELEMENT title 	(#PCDATA)>
]>

<playlist>
<!-- BFH - SONGS - S -->
	<text>
		<heading></heading>
		<title>PLAYLIST</title>	
	</text>
	<text>
		<heading></heading>
		<title>#</title>	
	</text>

<!-- 1 -->
<track>
	<path>audio/bfhtheme256kbps.mp3</path>
	<title>BFH - Theme song</title>
</track>

<!-- 2 -->
<track>
	<path>audio/bfhremix256kbps.mp3</path>
	<title>BFH - Theme remix</title>
</track>

<!-- 3 -->
<track>
	<path>audio/bfhringtone128kbps.mp3</path>
	<title>BFH - Ringtone</title>
</track>
<!-- BFH - SONGS - E -->
</playlist>